# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# require: rubocop-rspec

inherit_gem:
  bixby: bixby_default.yml

inherit_from: .rubocop_fixme.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'public/assets/**/*'
    - 'gems/**/*'
    - '.gitignore'

require: './lib/rubocop/cops/avalon/license_header'
Avalon/LicenseHeader:
  Enabled: true
