version: '3.2'

volumes:
  db-avalon:
  fedora:
  solr:
  bundle:
  npms:

networks:
  external:
  internal:

services:
  db-avalon:
    image: postgres
    volumes:
      - db-avalon:/data
    environment:
      - PGDATA=/data
      - POSTGRES_USER=postgres
      - POSTGRES_DB=avalon
    networks:
      internal:
  fedora:
    image: avalonmediasystem/fedora:4.7.5
    volumes:
      - fedora:/data
    environment:
      - JAVA_OPTIONS=${JAVA_OPTIONS} -Dfcrepo.modeshape.configuration=classpath:/config/file-simple/repository.json -Dfcrepo.home=/data
    networks:
      internal:
  solr:
    image: avalonmediasystem/solr:avalon-7.0
    volumes:
      - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - avalon
      - /opt/solr/avalon_conf
    networks:
      internal:
  hls:
    image: avalonmediasystem/nginx:avalon-7.0
    networks:
      external:
  redis:
    image: redis:alpine
    networks:
      internal:
  avalon:
    image: avalonmediasystem/avalon:7.0
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "/rails_init-dev.sh"
    depends_on:
      - db-avalon
      - fedora
      - solr
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres@db-avalon/avalon
      - REDIS_HOST=redis
      - FEDORA_URL=http://fedora:8080/fedora/rest
      - SOLR_URL=http://solr:8983/solr/avalon
      - WEBPACKER_NODE_MODULES_BIN_PATH=/home/app/node_modules/.bin
    volumes:
      - bundle:/usr/local/bundle
      - npms:/home/app/node_modules
    networks:
      external:
      internal:
