version: '3.2'

volumes:
  db-avalon:
  fedora:
  solr:
  bundle:
  npms:

networks:
  external:
  internal:

services:
  db-avalon: &db-avalon
    image: postgres:11-alpine
    environment:
      - PGDATA=/data
      - POSTGRES_USER=postgres
      - POSTGRES_DB=avalon
    volumes:
      - db-avalon:/data
    networks:
      internal:
  db-avalon-test:
    <<: *db-avalon
    volumes: []

  fedora: &fedora
    image: avalonmediasystem/fedora:4.7.5
    volumes:
      - fedora:/data
    environment:
      - JAVA_OPTIONS=${JAVA_OPTIONS} -Dfcrepo.modeshape.configuration=classpath:/config/file-simple/repository.json -Dfcrepo.home=/data
    networks:
      internal:
  fedora-test:
    <<: *fedora
    volumes: []

  solr: &solr
    image: avalonmediasystem/solr:avalon-7.0
    volumes:
      - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - avalon
      - /opt/solr/avalon_conf
    networks:
      internal:
  solr-test:
    <<: *solr
    volumes: 
      - ./solr/config:/opt/solr/avalon_conf

  hls:
    image: avalonmediasystem/nginx:avalon-7.0
    networks:
      external:

  redis: &redis
    image: redis:alpine
    networks:
      internal:
  redis-test:
    <<: *redis

  avalon: &avalon
    image: avalonmediasystem/avalon:7.0
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: "/rails_init-dev.sh"
    depends_on:
      - db-avalon
      - fedora
      - solr
      - redis
      - hls
    environment:
      - DATABASE_URL=postgresql://postgres@db-avalon/avalon
      - REDIS_HOST=redis
      - FEDORA_URL=http://fedora:8080/fedora/rest
      - SOLR_URL=http://solr:8983/solr/avalon
    volumes:
      - bundle:/usr/local/bundle
      - npms:/home/app/avalon/node_modules
    networks:
      external:
      internal:

  test:
    <<: *avalon
    command: >
      bash -c "/rails_init-dev.sh && tail -f /dev/null"
    depends_on:
      - db-avalon-test
      - fedora-test
      - solr-test
      - redis-test
    environment:
      - DATABASE_URL=postgresql://postgres@db-avalon-test/avalon
      - REDIS_HOST=redis-test
      - FEDORA_URL=http://fedora-test:8080/fedora/rest
      - SOLR_URL=http://solr-test:8983/solr/avalon
      - RAILS_ENV=test
      - BUNDLE_FLAGS=--with aws development test --without production
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true
    volumes: []
