attributes:

  date_issued:
    type: string
    multiple: false
    index_keys:
      - "date_issued_sim"
      - "date_issued_tesim"
    form:
      required: true
      primary: true

  physical_description:
    type: string
    multiple: true
    index_keys:
      - "physical_description_ssim"
      - "physical_description_tesim"
    form:
      required: false
      secondary: true

  genre:
    type: string
    multiple: true
    index_keys:
      - "genre_ssim"
    form:
      required: false
      secondary: true

  topical_subject:
    type: string
    multiple: true
    index_keys:
      - "topical_subject_ssim"
    form:
      required: false
      secondary: true

  temporal_subject:
    type: string
    multiple: true
    index_keys:
      - "temporal_subject_ssim"
    form:
      required: false
      secondary: true

  geographic_subject:
    type: string
    multiple: true
    index_keys:
      - "geographic_subject_ssim"
    form:
      required: false
      secondary: true

  permalink:
    type: string
    multiple: false
    index_keys:
      - "permalink_ssi"
    form:
      required: false
      secondary: true

  related_item:
    type: string
    multiple: false
    index_keys:
      - "related_item_ssi"
    form:
      required: false
      secondary: true

  # identifiers
  bibliographic_id:
    type: string
    multiple: false
    index_keys:
      - "bibliogrphic_id_ssi"
    form:
      required: false
      secondary: true

  local:
    type: string
    multiple: true
    index_keys:
      - "local_ssim"
    form:
      required: false
      secondary: true

  oclc:
    type: string
    multiple: true
    index_keys:
      - "oclc_ssim"
    form:
      required: false
      secondary: true

  lccn:
    type: string
    multiple: true
    index_keys:
      - "lccn_ssim"
    form:
      required: false
      secondary: true

  issue_number:
    type: integer
    mutiple: true
    index_keys:
      - "issue_number_isim"
    form:
      required: false
      secondary: true

  matrix_number:
    type: integer
    multiple: true
    index_keys:
      - "matrix_number_isim"
    form:
      required: false
      secondary: true

  music_publisher:
    type: string
    multiple: true
    index_keys:
      - "music_publisher_ssim"
    form:
      required: false
      secondary: true

  video_recording_identifier:
    type: integer
    multiple: true
    index_keys:
      - "video_recording_identifier_ssim"
    form:
      required: false
      secondary: true

  table_of_contents:
    type: string
    multiple: false
    index_keys:
      - "table_of_content_ssi"
    form:
      required: false
      secondary: true

  note:
    type: string
    multiple: false
    index_keys:
      - "note_ss"
    form:
      required: false
      secondary: true

  terms_of_use:
    type: string
    multiple: true
    index_keys:
      - "terms_of_use_ssim"
    form:
      required: false
      secondary: true

  