attributes:

  date_issued:
    type: string
    multiple: false
    index_keys:
      - "date_issued_si"
      - "date_issued_tesi"
    form:
      required: true
      primary: true

  date_created:
    type: date_time
    multiple: true
    index_keys:
      - "date_created_tesim"
    form:
      primary: false

  creator:
    type: string
    multiple: true
    index_keys:
      - "creator_ssim"
      - "creator_tesim"
    form:
      required: false
      primary: false

  contributor:
    type: string
    multiple: true
    index_keys:
      - "contributor_ssim"
      - "contributor_tesim"
    form:
      primary: false

  publisher:
    type: string
    multiple: true
    index_keys:
      - "publisher_ssim"
      - "publisher_tesim"
    form:
      primary: false

  abstract:
    type: string
    multiple: true
    index_keys:
      - "abstract_ssim"
      - "abstract_tesim"
    form:
      primary: false

  physical_description:
    type: string
    multiple: false
    index_keys:
      - "physical_description_ssi"
      - "physical_description_tesi"
    form:
      required: false
      primary: false

  language:
    type: string
    multiple: true
    index_keys:
      - "language_ssim"
      - "language_tesim"
    form:
      primary: false

  genre:
    type: string
    multiple: true
    index_keys:
      - "genre_ssim"
      - "genre_tesim"
    form:
      required: false
      primary: false

  topical_subject:
    type: string
    multiple: true
    index_keys:
      - "topical_subject_ssim"
      - "topical_subject_tesim"
    form:
      required: false
      primary: false

  temporal_subject:
    type: string
    multiple: true
    index_keys:
      - "temporal_subject_ssim"
      - "temporal_subject_tesim"
    form:
      required: false
      primary: false

  geographic_subject:
    type: string
    multiple: true
    index_keys:
      - "geographic_subject_ssim"
      - "geographic_subject_tesim"
    form:
      required: false
      primary: false

  permalink:
    type: string
    multiple: true
    index_keys:
      - "permalink_ssim"
      - "permalink_tesim"
    form:
      required: false
      primary: false

  related_item:
    type: string
    multiple: false
    index_keys:
      - "related_item_ssi"
      - "related_item_tesi"
    form:
      required: false
      primary: false


  # identifiers
  bibliographic_id:
    type: string
    multiple: false
    index_keys:
      - "bibliographic_id_ssi"
      - "bibliographic_id_tesi"
    form:
      required: false
      primary: false

  local:
    type: string
    multiple: true
    index_keys:
      - "local_ssim"
      - "local_tesim"
    form:
      required: false
      primary: false

  oclc:
    type: string
    multiple: true
    index_keys:
      - "oclc_ssim"
      - "oclc_tesim"
    form:
      required: false
      primary: false

  lccn:
    type: string
    multiple: true
    index_keys:
      - "lccn_ssim"
      - "lccn_tesim"
    form:
      required: false
      primary: false

  issue_number:
    type: integer
    mutiple: true
    index_keys:
      - "issue_number_isim"
      - "issue_number_tesim"
    form:
      required: false
      primary: false

  matrix_number:
    type: integer
    multiple: true
    index_keys:
      - "matrix_number_isim"
      - "matrix_number_tesim"
    form:
      required: false
      primary: false

  music_publisher:
    type: string
    multiple: true
    index_keys:
      - "music_publisher_ssim"
      - "music_publisher_tesim"
    form:
      required: false
      primary: false

  video_recording_identifier:
    type: integer
    multiple: true
    index_keys:
      - "video_recording_identifier_ssim"
      - "video_recording_identifier_tesim"
    form:
      required: false
      primary: false

  table_of_contents:
    type: string
    multiple: false
    index_keys:
      - "table_of_contents_ssi"
      - "table_of_contents_tesi"
    form:
      required: false
      primary: false

  note:
    type: string
    multiple: false
    index_keys:
      - "note_ss"
    form:
      required: false
      primary: false

  rights_statement:
    type: string
    multiple: false
    index_keys:
      - "rights_statement_ssi"
      - "rights_statement_tesi"
    form:
      primary: false

  license:
    type: string
    multiple: true
    index_keys:
      - "license_ssim"
      - "license_tesim"
    form:
      primary: false

  terms_of_use:
    type: string
    multiple: true
    index_keys:
      - "terms_of_use_ssim"
      - "terms_of_use_tesim"
    form:
      required: false
      primary: false