attributes:

  date_issued:
    type: string
    multiple: false
    index_keys:
      - "date_issued_sim"
      - "date_issued_tesim"
    form:
      required: true
      primary: true

  date_created:
    type: date_time
    multiple: true
    index_keys:
      - "date_created_dtsim"
    form:
      primary: false

  creator:
    type: string
    multiple: true
    index_keys:
      - "creator_ssim"
    form:
      required: false
      primary: false

  contributor:
    type: string
    multiple: true
    index_keys:
      - "contributor_ssim"
    form:
      primary: false

  publisher:
    type: string
    multiple: true
    index_keys:
      - "publisher_ssim"
    form:
      primary: false

  abstract:
    type: string
    multiple: true
    index_keys:
      - "abstract_ssim"
      - "abstract_tesim"
    form:
      primary: false

  physical_description:
    type: string
    multiple: false
    index_keys:
      - "physical_description_ssim"
      - "physical_description_tesim"
    form:
      required: false
      primary: false

  language:
    type: string
    multiple: true
    index_keys:
      - "language_ssim"
    form:
      primary: false

  genre:
    type: string
    multiple: true
    index_keys:
      - "genre_ssim"
    form:
      required: false
      primary: false

  topical_subject:
    type: string
    multiple: true
    index_keys:
      - "topical_subject_ssim"
    form:
      required: false
      primary: false

  temporal_subject:
    type: string
    multiple: true
    index_keys:
      - "temporal_subject_ssim"
    form:
      required: false
      primary: false

  geographic_subject:
    type: string
    multiple: true
    index_keys:
      - "geographic_subject_ssim"
    form:
      required: false
      primary: false

  permalink:
    type: string
    multiple: true
    index_keys:
      - "permalink_ssim"
    form:
      required: false
      primary: false

  related_item:
    type: string
    multiple: false
    index_keys:
      - "related_item_ssi"
    form:
      required: false
      primary: false


  # identifiers
  bibliographic_id:
    type: string
    multiple: false
    index_keys:
      - "bibliogrphic_id_ssi"
    form:
      required: false
      primary: false

  local:
    type: string
    multiple: true
    index_keys:
      - "local_ssim"
    form:
      required: false
      primary: false

  oclc:
    type: string
    multiple: true
    index_keys:
      - "oclc_ssim"
    form:
      required: false
      primary: false

  lccn:
    type: string
    multiple: true
    index_keys:
      - "lccn_ssim"
    form:
      required: false
      primary: false

  issue_number:
    type: integer
    mutiple: true
    index_keys:
      - "issue_number_isim"
    form:
      required: false
      primary: false

  matrix_number:
    type: integer
    multiple: true
    index_keys:
      - "matrix_number_isim"
    form:
      required: false
      primary: false

  music_publisher:
    type: string
    multiple: true
    index_keys:
      - "music_publisher_ssim"
    form:
      required: false
      primary: false

  video_recording_identifier:
    type: integer
    multiple: true
    index_keys:
      - "video_recording_identifier_ssim"
    form:
      required: false
      primary: false

  table_of_contents:
    type: string
    multiple: false
    index_keys:
      - "table_of_content_ssi"
    form:
      required: false
      primary: false

  note:
    type: string
    multiple: false
    index_keys:
      - "note_ss"
    form:
      required: false
      primary: false

  rights_statement:
    type: string
    multiple: false
    index_keys:
      - "rights_statement_ssi"
    form:
      primary: false

  license:
    type: string
    multiple: true
    index_keys:
      - "license_ssim"
    form:
      primary: false

  terms_of_use:
    type: string
    multiple: true
    index_keys:
      - "terms_of_use_ssim"
    form:
      required: false
      primary: false