development:
  host: <%= Settings.redis.host || "localhost" %>
  port: <%= Settings.redis.port || "6379" %>
test:
  host: <%= Settings.redis.host || "localhost" %>
  port: <%= Settings.redis.port || "6379" %>
production:
  host: <%= Settings.redis.host || "localhost" %>
  port: <%= Settings.redis.port || "6379" %>
