development:
  host: <%= ENV["REDIS_HOST"] || "localhost" %>
  port: <%= ENV["REDIS_HOST"] || "6379" %>
test:
  host: <%= ENV["REDIS_HOST"] || "localhost" %>
  port: <%= ENV["REDIS_HOST"] || "6379" %>
production:
  host: <%= ENV["REDIS_HOST"] || "localhost" %>
  port: <%= ENV["REDIS_HOST"] || "6379" %>
